const data = [
  {
    id: 1,
    text: "ana tawfik",
    from: "tawfik",
    audio: "/aud.wav",
    image: "/cover.png",
  },
  {
    id: 3,
    text: "ana amany",
    from: "amany",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 2,
    text: "ana omniea",
    from: "nejm",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 4,
    text: "ana negm",
    from: "ayat",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 5,
    text: "ana nagy",
    from: "fgh",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 6,
    text: "ana hady",
    from: "cvb",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 7,
    text: "ana tamer",
    from: "asd",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 8,
    text: "ana amr",
    from: "lkj",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 9,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "poi",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 10,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "joh",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 11,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "doe",
    audio: "",
    image: "/cover.png",
  },
  {
    id: 12,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "gif",
    audio: "",
    image: "/cover.png",
  },
];

export default data;
