const data = [
  {
    id: 1,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "tawfik",
    src: "/aud.wav",
    image: "/cover.png",
  },
  {
    id: 3,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "amany",
    src: "",
    image: "/cover.png",
  },
  {
    id: 2,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "nejm",
    src: "",
    image: "/cover.png",
  },
  {
    id: 4,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "ayat",
    src: "",
    image: "/cover.png",
  },
  {
    id: 5,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "fgh",
    src: "",
    image: "/cover.png",
  },
  {
    id: 6,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "cvb",
    src: "",
    image: "/cover.png",
  },
  {
    id: 7,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "asd",
    src: "",
    image: "/cover.png",
  },
  {
    id: 8,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "lkj",
    src: "",
    image: "/cover.png",
  },
  {
    id: 9,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "poi",
    src: "",
    image: "/cover.png",
  },
  {
    id: 10,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "joh",
    src: "",
    image: "/cover.png",
  },
  {
    id: 11,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "doe",
    src: "",
    image: "/cover.png",
  },
  {
    id: 12,
    text: "Happy Birthday Dr/Radwa i hope you the best",
    from: "gif",
    src: "",
    image: "/cover.png",
  },
];

export default data;
